/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PagoPendienteRouteImport } from './routes/pago.pendiente'
import { Route as PagoExitoRouteImport } from './routes/pago.exito'
import { Route as PagoErrorRouteImport } from './routes/pago.error'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppProgresoRouteImport } from './routes/app.progreso'
import { Route as AppPlusRouteImport } from './routes/app.plus'
import { Route as AppCategoriasRouteImport } from './routes/app.categorias'
import { Route as AppAjustesRouteImport } from './routes/app.ajustes'
import { Route as AppQuizIndexRouteImport } from './routes/app/quiz/index'
import { Route as AppQuizSessionRouteImport } from './routes/app/quiz/session'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PagoPendienteRoute = PagoPendienteRouteImport.update({
  id: '/pago/pendiente',
  path: '/pago/pendiente',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoExitoRoute = PagoExitoRouteImport.update({
  id: '/pago/exito',
  path: '/pago/exito',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoErrorRoute = PagoErrorRouteImport.update({
  id: '/pago/error',
  path: '/pago/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProgresoRoute = AppProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => AppRoute,
} as any)
const AppPlusRoute = AppPlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizIndexRoute = AppQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizSessionRoute = AppQuizSessionRouteImport.update({
  id: '/quiz/session',
  path: '/quiz/session',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ajustes': typeof AppAjustesRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/plus': typeof AppPlusRoute
  '/app/progreso': typeof AppProgresoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/pago/error': typeof PagoErrorRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/app/': typeof AppIndexRoute
  '/app/quiz/session': typeof AppQuizSessionRoute
  '/app/quiz/': typeof AppQuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/plus': typeof AppPlusRoute
  '/app/progreso': typeof AppProgresoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/pago/error': typeof PagoErrorRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/app': typeof AppIndexRoute
  '/app/quiz/session': typeof AppQuizSessionRoute
  '/app/quiz': typeof AppQuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ajustes': typeof AppAjustesRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/plus': typeof AppPlusRoute
  '/app/progreso': typeof AppProgresoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/pago/error': typeof PagoErrorRoute
  '/pago/exito': typeof PagoExitoRoute
  '/pago/pendiente': typeof PagoPendienteRoute
  '/app/': typeof AppIndexRoute
  '/app/quiz/session': typeof AppQuizSessionRoute
  '/app/quiz/': typeof AppQuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/ajustes'
    | '/app/categorias'
    | '/app/plus'
    | '/app/progreso'
    | '/auth/login'
    | '/auth/register'
    | '/pago/error'
    | '/pago/exito'
    | '/pago/pendiente'
    | '/app/'
    | '/app/quiz/session'
    | '/app/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/ajustes'
    | '/app/categorias'
    | '/app/plus'
    | '/app/progreso'
    | '/auth/login'
    | '/auth/register'
    | '/pago/error'
    | '/pago/exito'
    | '/pago/pendiente'
    | '/app'
    | '/app/quiz/session'
    | '/app/quiz'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/ajustes'
    | '/app/categorias'
    | '/app/plus'
    | '/app/progreso'
    | '/auth/login'
    | '/auth/register'
    | '/pago/error'
    | '/pago/exito'
    | '/pago/pendiente'
    | '/app/'
    | '/app/quiz/session'
    | '/app/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  PagoErrorRoute: typeof PagoErrorRoute
  PagoExitoRoute: typeof PagoExitoRoute
  PagoPendienteRoute: typeof PagoPendienteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/pago/pendiente': {
      id: '/pago/pendiente'
      path: '/pago/pendiente'
      fullPath: '/pago/pendiente'
      preLoaderRoute: typeof PagoPendienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/exito': {
      id: '/pago/exito'
      path: '/pago/exito'
      fullPath: '/pago/exito'
      preLoaderRoute: typeof PagoExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/error': {
      id: '/pago/error'
      path: '/pago/error'
      fullPath: '/pago/error'
      preLoaderRoute: typeof PagoErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/progreso': {
      id: '/app/progreso'
      path: '/progreso'
      fullPath: '/app/progreso'
      preLoaderRoute: typeof AppProgresoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plus': {
      id: '/app/plus'
      path: '/plus'
      fullPath: '/app/plus'
      preLoaderRoute: typeof AppPlusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categorias': {
      id: '/app/categorias'
      path: '/categorias'
      fullPath: '/app/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ajustes': {
      id: '/app/ajustes'
      path: '/ajustes'
      fullPath: '/app/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz/': {
      id: '/app/quiz/'
      path: '/quiz'
      fullPath: '/app/quiz/'
      preLoaderRoute: typeof AppQuizIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz/session': {
      id: '/app/quiz/session'
      path: '/quiz/session'
      fullPath: '/app/quiz/session'
      preLoaderRoute: typeof AppQuizSessionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAjustesRoute: typeof AppAjustesRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppPlusRoute: typeof AppPlusRoute
  AppProgresoRoute: typeof AppProgresoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppQuizSessionRoute: typeof AppQuizSessionRoute
  AppQuizIndexRoute: typeof AppQuizIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAjustesRoute: AppAjustesRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppPlusRoute: AppPlusRoute,
  AppProgresoRoute: AppProgresoRoute,
  AppIndexRoute: AppIndexRoute,
  AppQuizSessionRoute: AppQuizSessionRoute,
  AppQuizIndexRoute: AppQuizIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  PagoErrorRoute: PagoErrorRoute,
  PagoExitoRoute: PagoExitoRoute,
  PagoPendienteRoute: PagoPendienteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
